### ISSUE TITLE
we should consider adding ignore_case, single line, and multiline behavior support to the ios:line_test

### ISSUE THREAD

**Issue by djhaynes** [OVAL-Community/Language#108]
We should consider adding ignore_case, single line, and multiline behavior
support to the ios:line_test to allow for better processing of the show command
output which may contain multiple lines of data.

Please see the following links for additional information.

http://making-security-measurable.1364806.n2.nabble.com/Behavior-proposal-for-line-object-ios-tp6612121p6612121.html

http://www.jaytmedia.com/cisco/ios.html#show

**Comment by solind** [comment]
This was an interesting and compelling proposal, which was completely ignored when Cisco added three completely new schemas to OVAL 5.11!  Too bad!

If it were to be added, we'd need something like a new ios:line511_test, because it would require the addition of an instance entity to the line_object to work like the textfilecontent54_test.

I'll push this to 5.12, perhaps Cisco will want to add this...

**Comment by zport** [comment]
Issue moved to [OVAL-Community/OVAL #58](https://github.com/OVAL-Community/OVAL/issues/58) via [**ZenHub**](https://www.zenhub.com/)
