### ISSUE TITLE
consider whether or not the linux-def:partition_test belongs in the UNIX schema

### ISSUE THREAD

**Issue by djhaynes** [OVAL-Community/Language#116]
The linux-def:partition_test may apply to other UNIX-like platforms beyond
Linux.  We should consider whether or not the linux-def:partition_test belongs
in the UNIX schema or not.  Please see the following oval-developer-list posts
for additional information.

http://making-security-measurable.1364806.n2.nabble.com/RFC-New-items-for-Linux-td4785229.html

http://making-security-measurable.1364806.n2.nabble.com/The-partition-object-in-the-Linux-schema-should-be-Unix-td6424124.html

**Comment by jlcharton** [comment]
Hi,

Is there any update on this topic?
I recently asked the openscap team for the same kind of issue: https://github.com/OpenSCAP/openscap/issues/899.

As I told them, I really don't see any reason for the partition_test, partition_object and partition_state to be Linux specific. All Unices I know (AIX, Solaris, HP-UX, BSD, ...) work with partitions, mount points, mount options, ...

Without partition_xxx definitions, do you know how one can check for mount points properties on non Linux Unices just using the core, independent or Unix probes?

Best regards,

Jean-Louis Charton

**Comment by solind** [comment]
Hi Jean-Louis,

I would speculate that nobody has advocated strongly for this because nobody has wanted (yet) to create OVAL content that needs to check this information outside of the Linux OS.  Do you have a use-case to create OVAL content that will need to do this?

The community is still working on a governance process for evolving the language.  You could certainly get things moving yourself if you were to produce an OVAL schema document specifying the new test/object/state/item types you think are important.  There are many examples in the [Sandbox project](https://github.com/OVALProject/Sandbox).

Alternatively, if you are writing an XCCDF benchmark, you could consider using the SCE check system to implement your rule(s).

Best regards,
--David Solin

**Comment by zport** [comment]
Issue moved to [OVAL-Community/OVAL #56](https://github.com/OVAL-Community/OVAL/issues/56) via [**ZenHub**](https://www.zenhub.com/)
