### ISSUE TITLE
document how to handle cmdlet properties without names

### ISSUE THREAD

**Issue by djhaynes** [OVAL-Community/Language#188]
It seems it is possible for cmdlet properties to not have names (i.e. a cmdlet that just returns string values).  However, names are required in field entities.  We need to specify how situations like this should be handled in OVAL such that tools and content authors are handling it in the same way and content can be interoperable.

**Comment by solind** [comment]
Well, this is complicated.

In Powershell, everything in a pipeline is an object.  Even a string is an object; it has Property called Length, and a ParameterizedProperty called Chars(int index).  The cmdlet_test is nice because it is supposed to handle arbitrary objects (although in practice it can't handle complex member properties very well unless they're just simple arrays or lists).

Joval detects if the pipeline is spitting out strings, and in that case, it creates fields named "length" and "chars", containing the Length Property value and the string chars, respectively.  That was our interpretation of what to do.

Alternatively, we could document that, if the pipeline returns strings, the records should have fields with name="" and value=(string value).

Does anyone else have any thoughts?  I'll punt this issue to 5.12 for now.

**Comment by zport** [comment]
Issue moved to [OVAL-Community/OVAL #39](https://github.com/OVAL-Community/OVAL/issues/39) via [**ZenHub**](https://www.zenhub.com/)
